language: java
jdk:
  - openjdk8

# only build for commits/pr targeted to master branch
# this avoid duplicate builds for push+PR
branches:
  only:
    - master
script:
  - mvn verify jacoco:report
after_success:
  - mvn coveralls:report